[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "keyfile.toml"

[proxypool]
source = "github"
github = "qculug/proxypool"

[tor]
source = "cmd"
cmd = "curl -s https://git.alpinelinux.org/aports/plain/community/tor/APKBUILD | grep '^pkgver=' | awk -F '=' '{print $2}'"

[v2ray]
source = "github"
github = "v2fly/v2ray-core"
use_latest_tag = true
from_pattern = 'v(\d+).(\d+).(\d+)'
to_pattern = '\1.\2.\3'

[shadowsocks-libev]
source = "cmd"
cmd = "curl -s https://git.alpinelinux.org/aports/plain/testing/shadowsocks-libev/APKBUILD | grep '^pkgver=' | awk -F '=' '{print $2}'"
