name: build dockerfiles
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: build and push docker image to ghcr.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfiles: [proxypool, tor]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms:
            linux/amd64,linux/arm,linux/arm64
          context: .
          file: ${{ matrix.dockerfiles }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.dockerfiles }}:latest
