name: build dockerfiles
on:
  push:
    paths:
      - 'new_ver.json'

jobs:
  build:
    name: build and push docker image to ghcr.io
    runs-on: ubuntu-latest
    container:
      image: docker.io/archlinux:latest
    strategy:
      fail-fast: false
      matrix:
        dockerfiles: [proxypool, tor]
    steps:
      - name: Install git
        run: |
          pacman -Sy --noconfirm git
      - name: Git pull from ${{ github.repository }}
        run: |
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.repository }}
          cd ${{ github.repository }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms:
            linux/amd64,linux/arm,linux/arm64
          context: ${{ github.repository }}
          file: ${{ matrix.dockerfiles }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.dockerfiles }}:latest
      - name: Install nvchecker
        run: |
          pacman -Sy --noconfirm nvchecker
      - name: Run nvtake
        run: |
          nvtake --file nvchecker.toml ${{ matrix.dockerfiles }}
      - name: Git push to ${{ github.repository }}
        run: |
          cd ${{ github.repository }}
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add old_ver.json
          git commit -m "update: old_ver.json"
          git pull --rebase
          git push
