name: build dockerfiles
on:
  push:
    paths:
      - 'new_ver.json'

jobs:
  build:
    name: build and push docker image to ghcr.io
    runs-on: ubuntu-latest
    container:
      image: docker.io/archlinux:latest
    strategy:
      fail-fast: false
      matrix:
        dockerfiles: [proxypool, tor]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms:
            linux/amd64,linux/arm,linux/arm64
          context: .
          file: ${{ matrix.dockerfiles }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.dockerfiles }}:latest
      - name: Install nvchecker
        run: |
          pacman -Sy --noconfirm git nvchecker
      - name: Run nvtake
        run: |
          nvtake --file nvchecker.toml ${{ matrix.dockerfiles }}
      - name: Git push to ${{ github.repository }}
        run: |
          git init
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add old_ver.json
          git remote add origin "https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/${{ github.repository }}"
          git push --set-upstream origin master
